/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: edcpayload.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "edcpayload.pb-c.h"
void   edc_payload__edc_metric__init
                     (EdcPayload__EdcMetric         *message)
{
  static EdcPayload__EdcMetric init_value = EDC_PAYLOAD__EDC_METRIC__INIT;
  *message = init_value;
}
void   edc_payload__edc_position__init
                     (EdcPayload__EdcPosition         *message)
{
  static EdcPayload__EdcPosition init_value = EDC_PAYLOAD__EDC_POSITION__INIT;
  *message = init_value;
}
void   edc_payload__init
                     (EdcPayload         *message)
{
  static EdcPayload init_value = EDC_PAYLOAD__INIT;
  *message = init_value;
}
size_t edc_payload__get_packed_size
                     (const EdcPayload *message)
{
  assert(message->base.descriptor == &edc_payload__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t edc_payload__pack
                     (const EdcPayload *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &edc_payload__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t edc_payload__pack_to_buffer
                     (const EdcPayload *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &edc_payload__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EdcPayload *
       edc_payload__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EdcPayload *)
     protobuf_c_message_unpack (&edc_payload__descriptor,
                                allocator, len, data);
}
void   edc_payload__free_unpacked
                     (EdcPayload *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &edc_payload__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
const ProtobufCEnumValue edc_payload__edc_metric__value_type__enum_values_by_number[7] =
{
  { "DOUBLE", "EDC_PAYLOAD__EDC_METRIC__VALUE_TYPE__DOUBLE", 0 },
  { "FLOAT", "EDC_PAYLOAD__EDC_METRIC__VALUE_TYPE__FLOAT", 1 },
  { "INT64", "EDC_PAYLOAD__EDC_METRIC__VALUE_TYPE__INT64", 2 },
  { "INT32", "EDC_PAYLOAD__EDC_METRIC__VALUE_TYPE__INT32", 3 },
  { "BOOL", "EDC_PAYLOAD__EDC_METRIC__VALUE_TYPE__BOOL", 4 },
  { "STRING", "EDC_PAYLOAD__EDC_METRIC__VALUE_TYPE__STRING", 5 },
  { "BYTES", "EDC_PAYLOAD__EDC_METRIC__VALUE_TYPE__BYTES", 6 },
};
static const ProtobufCIntRange edc_payload__edc_metric__value_type__value_ranges[] = {
{0, 0},{0, 7}
};
const ProtobufCEnumValueIndex edc_payload__edc_metric__value_type__enum_values_by_name[7] =
{
  { "BOOL", 4 },
  { "BYTES", 6 },
  { "DOUBLE", 0 },
  { "FLOAT", 1 },
  { "INT32", 3 },
  { "INT64", 2 },
  { "STRING", 5 },
};
const ProtobufCEnumDescriptor edc_payload__edc_metric__value_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EdcPayload.EdcMetric.ValueType",
  "ValueType",
  "EdcPayload__EdcMetric__ValueType",
  "",
  7,
  edc_payload__edc_metric__value_type__enum_values_by_number,
  7,
  edc_payload__edc_metric__value_type__enum_values_by_name,
  1,
  edc_payload__edc_metric__value_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor edc_payload__edc_metric__field_descriptors[9] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(EdcPayload__EdcMetric, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(EdcPayload__EdcMetric, type),
    &edc_payload__edc_metric__value_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "double_value",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(EdcPayload__EdcMetric, has_double_value),
    offsetof(EdcPayload__EdcMetric, double_value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "float_value",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(EdcPayload__EdcMetric, has_float_value),
    offsetof(EdcPayload__EdcMetric, float_value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "long_value",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(EdcPayload__EdcMetric, has_long_value),
    offsetof(EdcPayload__EdcMetric, long_value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "int_value",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(EdcPayload__EdcMetric, has_int_value),
    offsetof(EdcPayload__EdcMetric, int_value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bool_value",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(EdcPayload__EdcMetric, has_bool_value),
    offsetof(EdcPayload__EdcMetric, bool_value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "string_value",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(EdcPayload__EdcMetric, string_value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bytes_value",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(EdcPayload__EdcMetric, has_bytes_value),
    offsetof(EdcPayload__EdcMetric, bytes_value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned edc_payload__edc_metric__field_indices_by_name[] = {
  6,   /* field[6] = bool_value */
  8,   /* field[8] = bytes_value */
  2,   /* field[2] = double_value */
  3,   /* field[3] = float_value */
  5,   /* field[5] = int_value */
  4,   /* field[4] = long_value */
  0,   /* field[0] = name */
  7,   /* field[7] = string_value */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange edc_payload__edc_metric__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor edc_payload__edc_metric__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EdcPayload.EdcMetric",
  "EdcMetric",
  "EdcPayload__EdcMetric",
  "",
  sizeof(EdcPayload__EdcMetric),
  9,
  edc_payload__edc_metric__field_descriptors,
  edc_payload__edc_metric__field_indices_by_name,
  1,  edc_payload__edc_metric__number_ranges,
  (ProtobufCMessageInit) edc_payload__edc_metric__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor edc_payload__edc_position__field_descriptors[9] =
{
  {
    "latitude",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(EdcPayload__EdcPosition, latitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "longitude",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(EdcPayload__EdcPosition, longitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "altitude",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(EdcPayload__EdcPosition, has_altitude),
    offsetof(EdcPayload__EdcPosition, altitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "precision",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(EdcPayload__EdcPosition, has_precision),
    offsetof(EdcPayload__EdcPosition, precision),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "heading",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(EdcPayload__EdcPosition, has_heading),
    offsetof(EdcPayload__EdcPosition, heading),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "speed",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(EdcPayload__EdcPosition, has_speed),
    offsetof(EdcPayload__EdcPosition, speed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(EdcPayload__EdcPosition, has_timestamp),
    offsetof(EdcPayload__EdcPosition, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "satellites",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(EdcPayload__EdcPosition, has_satellites),
    offsetof(EdcPayload__EdcPosition, satellites),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(EdcPayload__EdcPosition, has_status),
    offsetof(EdcPayload__EdcPosition, status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned edc_payload__edc_position__field_indices_by_name[] = {
  2,   /* field[2] = altitude */
  4,   /* field[4] = heading */
  0,   /* field[0] = latitude */
  1,   /* field[1] = longitude */
  3,   /* field[3] = precision */
  7,   /* field[7] = satellites */
  5,   /* field[5] = speed */
  8,   /* field[8] = status */
  6,   /* field[6] = timestamp */
};
static const ProtobufCIntRange edc_payload__edc_position__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor edc_payload__edc_position__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EdcPayload.EdcPosition",
  "EdcPosition",
  "EdcPayload__EdcPosition",
  "",
  sizeof(EdcPayload__EdcPosition),
  9,
  edc_payload__edc_position__field_descriptors,
  edc_payload__edc_position__field_indices_by_name,
  1,  edc_payload__edc_position__number_ranges,
  (ProtobufCMessageInit) edc_payload__edc_position__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor edc_payload__field_descriptors[4] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(EdcPayload, has_timestamp),
    offsetof(EdcPayload, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(EdcPayload, position),
    &edc_payload__edc_position__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "metric",
    5000,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EdcPayload, n_metric),
    offsetof(EdcPayload, metric),
    &edc_payload__edc_metric__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "body",
    5001,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(EdcPayload, has_body),
    offsetof(EdcPayload, body),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned edc_payload__field_indices_by_name[] = {
  3,   /* field[3] = body */
  2,   /* field[2] = metric */
  1,   /* field[1] = position */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange edc_payload__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 5000, 2 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor edc_payload__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EdcPayload",
  "EdcPayload",
  "EdcPayload",
  "",
  sizeof(EdcPayload),
  4,
  edc_payload__field_descriptors,
  edc_payload__field_indices_by_name,
  2,  edc_payload__number_ranges,
  (ProtobufCMessageInit) edc_payload__init,
  NULL,NULL,NULL    /* reserved[123] */
};
